branch-protection: {}
deck:
  spyglass: {}
gerrit: {}
github:
  LinkURL: null
owners_dir_blacklist:
  default: null
  repos: null
plank: {}
presubmits: {}
push_gateway:
  serve_metrics: false
sinker: {}
tide:
  context_options:
    required-if-present-contexts: null