apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: RepositoryConfig
spec:
  presubmits:
  - name: lint
    context: "lint"
    alwaysRun: true
    optional: false
    trigger: "/lint"
    rerunCommand: "/relint"
  branchProtection:
    contexts:
    - lint

